### PR TITLE
#7 typescript support

### LINKED ISSUE #7: typescript support
Congrats its was very useful for me, following is my (incomplete) types for anyone have interest
index.d.ts
```typescript
type Offset = {
    left: number;
    height: number; 
    top: number;
}

type Pos= {
pos: number;
} & Offset

export function position(element: HTMLElement,pos?:number): Pos;
export function offset(element: HTMLElement): Offset;
```
(im not create a PR cause types it's incomplete and i don't want anyone blame me for trashing his/her code)

### PR DESCRIPTION
**Pull request by mnahkies**
fixes #7 and also upgrades dependencies, notably gulp to v4 in order to support building using node v12

### CODE REVIEW

**Comment by mnahkies** [comment]
@deshiknaves is there any chance you could take a look at this? It's a pretty trivial change

**Comment by deshiknaves** [comment]
I'll get this deployed next week Monday. Cheers

**Comment by mnahkies** [comment]
Awesome, thanks for that!

**Comment by deshiknaves** [comment]
I haven't published it yet because there are some security warnings. I will fix those and publish shortly.

**Pull request merged**
